---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-pvc
  namespace: myns
  labels: 
    app: mysql 
    name: mysql-pvc
spec: 
  storageClassName: do-block-storage
  accessModes: # an array can define a number of styles that fit ur use case, will pick one
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 1Gi
---
apiVersion: v1
kind: Deployment 
metadata: 
  name: mysql-deploy
  namespace: myns 
  labels: 
    app: mysql
    name: mysql-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
      name: mysql-po 
template: 
  metadata: 
    name: mysql-po 
    labels: 
      app: mysql
      name: mysql-po
  spec: 
    volumes: 
      - name: data-vol 
        persistantVolumeClaim:
          claimName: mysql-pvc
    containers:
      - name: mysql-container 
        image: mysql:8 
        imagePullPolicy: IfNotPresent
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: changeit
        ports: 
          - containerPort: 3306
        volumeMounts: 
          - name: data-vol 
            mountPath: /var/lib/mysql 


# ReadWriteOnce --> volume can only be mounted by 1 node (any pod on the node can mount the volume)
# ReadWriteOncePod --> volume can only be mounted to 1 POD (any other pod cannot mount it alr)