---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 
# list ur files that u can use
resources: 
  - ../../base # kustomization will go into the directory to look for the kustomization file, dont give the name of the file, just give dir.

labels: 
  - pairs: 
      env: development # will add this label too all resources 
    includeSelectors: true 
    includeTemplates: true 
namePrefix: dev 
namespace: devns


replicas: 
  - name: dov-deploy
    count: 1

images: 
  - name: chukmunnlee/cfdsa-dov-bear
    newName: chukmunnlee/dov-bear
    newTag: v5

configMapGenerator: 
  - name: dov-cm
    namespace: dovns 
    behavior: create 
    literals:  
      - NAME=fred
      - EMAIL=fred@gmail.com
secretGenerator: 
  - name: dov-secret
    namespace: dovns
    behavior: create 
    literals: 
      - NAME=sdfhsd
      - EMAIL=skdjfhsdkjfg

patches: 
  - target: 
      group: apps/v1
      kind: Deployment
      name: dov-deploy
    path: patches.yml
  - path: delete-ingress.yml

replacements:
  - source: 
      kind: service
      name: dov-svc # use original service name, before chaneg applied 
      namespace: dovns
      fieldPath: metadata.name
    targets: 
      - select: 
          kind: Deployment 
          name: dov-deploy
          namespace: dovns
        fieldPaths: 
          - spec.template.spec.containers.[name=dov-container].env.[name=SERVICE_NAME].value