---
# apiVersion, kind, metadata and spec are standard things that need to be defined. 
apiVersion: v1
kind: Pod 
metadata: 
  name: dov-po # need name cause kubernetes references the name. 
  namespace: myns
  labels: # organisation needs to set a label.
    app: dov
    name: dov-po
spec:
  containers: 
    - name: dov-container 
      image: chukmunnlee/cfdsa-dov-bear:v1.1
      imagePullPolicy: IfNotPresent # what to do when kubernetes wants to pull the image. --> can set to Never but node MUST have image preloaded.
      env: 
        - name: INSTANCE_NAME
          value: my-first-pod
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports: 
        - containerPort: 3000 # container port not the port on your local cluster. 
      # readinessProbe: # kubernetes checks if its ready (i.e. returns 200) before traffic is sent to it
      livenessProbe: # performed outside the container not inside, so no need curl.
        httpGet: # if dont set host, assume it is localhost 
          path: /healthz
          port: 3000


# status don't need to fill in, kubernetes will fill in for u. 