---
apiVersion: v1
kind: Namespace 
metadata: 
  name: mysqlns
  labels: 
    app: mysql
    name: mysqlns
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-hsvc
  namespace: mysqlns
  labels: 
    app: mysql
    name: mysql-hsvc 
spec: 
  clusterIP: None
  selector: 
    app: mysql
    name: mysql-po
  ports: 
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1 
kind: StatefulSet
metadata: 
  name: mysql-sts 
  namespace: mysqlns
  labels: 
    app: mysql
    name: mysql-sts 
spec: 
  serviceName: mysql-hsvc 
  replicas: 2 # 2 instances of mysql, NOT 2 clusters
  selector:
    matchLabels: 
      app: mysql
      name: mysql-po
  volumeClaimTemplates: 
    - metadata: 
        name: mysql-pvc 
        labels: 
          app: mysql 
          name: mysql-pvc 
      spec: 
        storageClassName: do-block-storage 
        accessModes: [ ReadWriteOncePod ] # only dedicate to the pod
        resources: 
          requests: 
            storage: 1Gi

  template: 
    metadata: 
      name: mysql-po 
      labels: 
        app: mysql 
        name: mysql-po 
    spec: 
      containers: 
        - name: mysql-container 
          image: mysql:8
          imagePullPolicy: IfNotPresent
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: changeit
          ports: 
            - containerPort: 3306
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
---
apiVersion: v1 
kind: Service 
metadata: 
  name: write-replica 
  namespace: mysqlns
  labels: 
    app: mysql 
    name: write-replica
spec: 
  type: ClusterIP 
  selector: 
    app: mysql 
    name: mysql-po
    apps.kubernetes.io/pod-index: "0"
  ports:
    - port: 3306 
      targetPort: 3306
---
apiVersion: v1 
kind: Service 
metadata: 
  name: read-replica 
  namespace: mysqlns
  labels: 
    app: mysql 
    name: read-replica
spec: 
  type: ClusterIP 
  selector: 
    app: mysql 
    name: mysql-po
  ports:
    - port: 3306 
      targetPort: 3306
